### ISSUE TITLE
Calling method from created hook

### ISSUE THREAD

**Issue by skegel13** [ffxsam/vue-typescript-cookbook#1]
When I try to call a method from my Vue component methods in the created hook, it tells me it does not exist. Do I need to add the method to an interface and extend it or is there something simpler.

Here's the example:

```
export default Vue.extend({
    created() {
        this.fetchData(); // VSCode tells me this method does not exist.
    },
    methods: {
        fetchData() {
            ...
        },
    },
});
```

**Comment by ffxsam** [comment]
That should work fine (I just tested it). Could you please post the full `.vue` file?

**Comment by skegel13** [comment]
Here's the full script tag. TSLint is picking up on anything and it is compiling fine, just VSCode with Vetur plugin telling me it doesn't exist.

```
<script lang="ts">
import { AxiosPromise } from 'axios';
import Vue, { VueConstructor } from 'vue';
import { createNamespacedHelpers } from 'vuex';
import Setting, { ISettingConfig } from '../models/setting.model';

interface IAdminSettingsPage {
    config: ISettingConfig[];
    findSetting: (name: string, value: string) => Setting;
    settings: Setting[];
    fetchSettings: () => AxiosPromise<Setting[]>;
}

const { mapActions, mapGetters, mapState } = createNamespacedHelpers('settings')

export default (Vue as VueConstructor<Vue & IAdminSettingsPage>).extend({
    name: 'TheAdminSettingsPage',

    props: {
        config: {
            type: Array,
            required: true,
        },
    },

    data() {
        return {
            settings: [],
        };
    },

    computed: {
        ...mapGetters(['findSetting']),
    },

    created() {
        this.fetchData();
    },

    methods: {
        ...mapActions(['fetchSettings']),

        async fetchData() {
            try {
                const response = await this.fetchSettings();
                this.settings = response.data;
            } catch (error) {
                console.log(error);
            }
        },
    },
});
</script>
```

**Comment by ffxsam** [comment]
So it sounds like an issue within VS Code only. Are you using the [TSLint Vue](https://marketplace.visualstudio.com/items?itemName=prograhammer.tslint-vue) extension? (not the standard TSLint extension)

**Comment by skegel13** [comment]
I was using the standard TSLint extension. I just added the TSLint Vue extension but it does not appear to have made a difference.

**Comment by ffxsam** [comment]
Oh, strange. I was able to replicate this too. I'll dig a bit and see if I can figure it out.

**Comment by ffxsam** [comment]
@skegel13 Ah yes. It's a bug in Vue + TS. You can't have prop of type "Array" at the moment. If you comment out the type, you'll see it works. So I just have TODO notes everywhere in my code to go back and put the Array type back in later, once it's fixed.

**Comment by ffxsam** [comment]
Additional info: https://github.com/vuejs/vue/pull/6856

**Comment by skegel13** [comment]
Yes, I kind of remember reading that awhile back before switching to class components. Thank you for pointing that out.
