### ISSUE TITLE
mapActions: property does not exist on type

### ISSUE THREAD

**Issue by amoe** [ffxsam/vue-typescript-cookbook#2]
The helper `mapActions` seems to suffer from the same problem as the problem described with `mapState` and `mapGetters`.  I'm betting that the solution described there also works for `mapActions`, but I'm not exactly sure what form it should take. 

For instance, marking the action as `any` will silence the error, but I feel like there's a more correct type for actions.  It might be good to have an example of the right type for actions.

```
import Vue, {VueConstructor} from 'vue';
import {mapActions} from 'vuex';

// Without this interface you get the following error
// 19:26 Property 'myAction' does not exist on type 'CombinedVueInstance<Vue, unknown, { doIt(): void; }, unknown, Readonly<Record<never, any>>>'.
interface VuexBindings {
    myAction: any;
}

export default (Vue as VueConstructor<Vue & VuexBindings>).extend({
    created() {
        console.log(this.myAction);
    },
    methods: {
        doIt() {
            console.log("doing a thing");
        },...mapActions(['myAction'])
    },
});
```

```
export default new Vuex.Store({
    state: {
    },
    mutations: {
    },
    actions: {
        myAction(store) {
            console.log("doing action");
        }
    },
    modules: {
    },
});
```

**Comment by ffxsam** [comment]
Hey @amoe! On a basic level, this would work:

```ts
interface VuexBindings {
  someAction: ({ name, url }: { name: string; url: string }) => boolean;
}
```

And then you'd call it:
```ts
this.someAction({ name: 'GitHub', url: 'https://github.com' });
```

Though it's a bummer to have to spell out that function type in every `.vue` file you want to use it in. You could export your function and do it this way:

```ts
import { someAction } from '@/store/actions';

interface VuexBindings {
  someAction: typeof someAction;
}
```

But I'm not a fan of that. I'll leave this issue open until there's an actual _good_ solution. 😄

**Comment by HIMISOCOOL** [comment]
vuex has next to no typescript support, its a real pain.
I have on my most recent project, cannibalized this pr from kstn
https://github.com/vuejs/vuex/pull/1121
There's a bit of work to make it compile in newer ts versions and I modified it from there to make it  work better for the class style syntax.
Ill try clean it up and post a gist here in the weekend but if you want results now you can try hack away at it
