### ISSUE TITLE
Could that maybe be part of the Vue documentation?

### ISSUE THREAD

**Issue by renestalder** [ffxsam/vue-typescript-cookbook#3]
You hit the nail on it's head with your guide here. There is so much useful information my team and I missed from the official documentation, with no clear answers on the web, what the approach is to solve these common problems.

Did you ever consider trying to push this information as pull request to the Vue 2.0 documentation?

**Comment by ffxsam** [comment]
Hey @renestalder! With Vue 3.0 around the corner, I'd probably hold off and see how things generally work with Vue + TS in the future.

Glad this cookbook was helpful to you and your team!
